#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
./script/update

test -z "$JEE_ENV" && JEE_ENV='development'

# boot the app and any other necessary processes.
./gradlew run
