#!/bin/sh

# script/test: Run test suite for application.

set -e
cd "$(dirname "$0")/.."

if [ "${JEE_ENV}" = "test" ] || [ "${JEE_ENV}" = "test" ]; then
    # if executed and the environment is already set to `test`, then we want a
    # clean from scratch application. This almost always means a ci environment,
    # since we set the environment to `test` directly in `script/cibuild`.
    ./script/setup
else
    # if the environment isn't set to `test`, set it to `test` and update the
    # application to ensure all dependencies are met as well as any other things
    # that need to be up to date, like db migrations. The environement not having
    # already been set to `test` almost always means this is being called on it's
    # own from a `development` environment.
    export JEE_ENV="test" JEE_ENV="test"
    ./script/update
fi

echo "===> Running tests..."
./gradlew test
